// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTlAX86wk-QabCYhfWvbc5BLC1O5u01SE',
    appId: '1:877956986270:web:1fed93925936f762a1d28f',
    messagingSenderId: '877956986270',
    projectId: 'flutter-uas-app',
    authDomain: 'flutter-uas-app.firebaseapp.com',
    storageBucket: 'flutter-uas-app.appspot.com',
    measurementId: 'G-68TD3S2128',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ2xVrArJTuwfBlLIbOq94auOjSD-vMvI',
    appId: '1:877956986270:android:574b69cf219b49aca1d28f',
    messagingSenderId: '877956986270',
    projectId: 'flutter-uas-app',
    storageBucket: 'flutter-uas-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALC5qSAUYqfEhDlyc1Y9aV01pxywSVLZA',
    appId: '1:877956986270:ios:d1150c7c80d77916a1d28f',
    messagingSenderId: '877956986270',
    projectId: 'flutter-uas-app',
    storageBucket: 'flutter-uas-app.appspot.com',
    iosClientId: '877956986270-e6a17qjne36bar9oog2pqpsnd5g9tss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantApp',
  );
}
